#devtools
alias ec="emacsclient -c . &"
alias spi="ssh root@10.9.8.2"
alias gs="git status"
alias e="emacs . &"
alias et="emacsclient -t ."
alias ne="nix-shell --command 'emacs . &'"
alias remacs="pkill emacs && emacs --daemon"

#files
alias la="ls -lah"
alias al="ls -lah"
alias rf="rm -rf"
alias cd..="cd .."
alias n="nnn"
alias r="ranger ."

#unsorted
alias chat="ssh bun@chat.shazow.net"
alias z="zathura"
alias inst="sudo apt install -y"
alias remo="sudo apt autoremove -y"
alias upgr="sudo apt update && sudo apt upgrade -y"
alias gl="git log --graph"
alias gd="git diff"
alias gp="git pull"
alias c="clear"
alias n="nix-shell"
alias sus="sudo sh -c 'echo mem > /sys/power/state' &"
alias remacs="pkill emacs && emacs --daemon"
alias cd..="cd .."
alias n="nnn"
alias et="emacsclient -t ."
alias rf="rm -rf"
alias cp="cp -i"
alias mv="mv -i"
