icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#24283b"
idle_fg = "#c0caf5"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "disk_space"
info_type = "available"
unit = "GB"
interval = 1

[[block]]
block = "net"
device = "wlp6s6"
speed_up = false
speed_down = false

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "time"